### ISSUE TITLE
String types should provide `#contains()`

### ISSUE THREAD

**Issue by mwsis** [synesissoftware/STLSoft-1.11#2]
Recently released **1.11.1-alpha1** of [**STLSoft-11**](https://github.com/synesissoftware/STLSoft-1.11) adds `#starts_with()` and `#ends_with()` to `stlsoft::basic_simple_string<>` and `stlsoft::basic_static_string()`.

Required is to add complementary `#contains()` method, which obtains `true` if the given string (or character) argument is found anywhere within the string; `false` otherwise.

**Definitition of Done**:
* 3-overloads of `#ends_with()` declared and implemented in `stlsoft::basic_simple_string<>()`, and suitable test cases added to **test.unit.stlsoft.string.simple_string** project;
* 3-overloads of `#ends_with()` declared and implemented in `stlsoft::basic_static_string<>()`, and suitable test cases added to **test.unit.stlsoft.string.simple_string** project;

**Comment by mwsis** [comment]
**NOTE**: we're now working on [**STLSoft-1.11**](https://github.com/synesissoftware/STLSoft-1.11), not **STLSoft-1.10** (as has been the case last few weeks).

**Comment by synesissoftware** [comment]
This complete as of **1.11.1-alpha3**
